/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BudgetItemType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const BudgetItem = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'itemType' : BudgetItemType,
  'amount' : IDL.Nat,
});
export const Recurrence = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const CalendarEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'title' : IDL.Text,
  'endTime' : IDL.Opt(Time),
  'description' : IDL.Text,
  'recurrence' : IDL.Opt(Recurrence),
  'taskId' : IDL.Opt(IDL.Nat),
});
export const CryptoEntry = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'updatedAt' : Time,
  'currentPriceCents' : IDL.Nat,
  'amount' : IDL.Nat,
  'purchasePriceCents' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'targetDate' : IDL.Opt(Time),
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'thursday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const TaskType = IDL.Variant({
  'weekend' : IDL.Null,
  'dayOfWeek' : DayOfWeek,
  'daily' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'taskType' : TaskType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBudgetItem' : IDL.Func(
      [IDL.Nat, IDL.Text, Time, BudgetItemType],
      [BudgetItem],
      [],
    ),
  'createCalendarEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Opt(Time),
        IDL.Opt(Recurrence),
        IDL.Opt(IDL.Nat),
      ],
      [CalendarEntry],
      [],
    ),
  'createCryptoEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [CryptoEntry],
      [],
    ),
  'createGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(Time)], [Goal], []),
  'createRecurringEntry' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Opt(Time), Recurrence],
      [CalendarEntry],
      [],
    ),
  'createTask' : IDL.Func([IDL.Text, IDL.Opt(Time), TaskType], [Task], []),
  'deleteBudgetItem' : IDL.Func([IDL.Nat], [], []),
  'deleteCalendarEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteCryptoEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getBudgetItems' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BudgetItem)],
      ['query'],
    ),
  'getCalendarEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CalendarEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCryptoPortfolio' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CryptoEntry)],
      ['query'],
    ),
  'getGoals' : IDL.Func([IDL.Principal], [IDL.Vec(Goal)], ['query']),
  'getRecurringEntries' : IDL.Func([], [IDL.Vec(CalendarEntry)], ['query']),
  'getTasks' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], []),
  'updateBudgetItem' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, Time, BudgetItemType],
      [IDL.Opt(BudgetItem)],
      [],
    ),
  'updateCalendarEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Opt(Time),
        IDL.Opt(Recurrence),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Opt(CalendarEntry)],
      [],
    ),
  'updateCryptoEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Opt(CryptoEntry)],
      [],
    ),
  'updateGoal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time)],
      [IDL.Opt(Goal)],
      [],
    ),
  'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Goal)], []),
  'updateRecurringEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Opt(Time), Recurrence],
      [IDL.Opt(CalendarEntry)],
      [],
    ),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(Time), TaskType],
      [IDL.Opt(Task)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BudgetItemType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const BudgetItem = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'itemType' : BudgetItemType,
    'amount' : IDL.Nat,
  });
  const Recurrence = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const CalendarEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'title' : IDL.Text,
    'endTime' : IDL.Opt(Time),
    'description' : IDL.Text,
    'recurrence' : IDL.Opt(Recurrence),
    'taskId' : IDL.Opt(IDL.Nat),
  });
  const CryptoEntry = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'updatedAt' : Time,
    'currentPriceCents' : IDL.Nat,
    'amount' : IDL.Nat,
    'purchasePriceCents' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'targetDate' : IDL.Opt(Time),
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'thursday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const TaskType = IDL.Variant({
    'weekend' : IDL.Null,
    'dayOfWeek' : DayOfWeek,
    'daily' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'taskType' : TaskType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBudgetItem' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, BudgetItemType],
        [BudgetItem],
        [],
      ),
    'createCalendarEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Opt(Time),
          IDL.Opt(Recurrence),
          IDL.Opt(IDL.Nat),
        ],
        [CalendarEntry],
        [],
      ),
    'createCryptoEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [CryptoEntry],
        [],
      ),
    'createGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(Time)], [Goal], []),
    'createRecurringEntry' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Opt(Time), Recurrence],
        [CalendarEntry],
        [],
      ),
    'createTask' : IDL.Func([IDL.Text, IDL.Opt(Time), TaskType], [Task], []),
    'deleteBudgetItem' : IDL.Func([IDL.Nat], [], []),
    'deleteCalendarEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteCryptoEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getBudgetItems' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BudgetItem)],
        ['query'],
      ),
    'getCalendarEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CalendarEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCryptoPortfolio' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CryptoEntry)],
        ['query'],
      ),
    'getGoals' : IDL.Func([IDL.Principal], [IDL.Vec(Goal)], ['query']),
    'getRecurringEntries' : IDL.Func([], [IDL.Vec(CalendarEntry)], ['query']),
    'getTasks' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], []),
    'updateBudgetItem' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, Time, BudgetItemType],
        [IDL.Opt(BudgetItem)],
        [],
      ),
    'updateCalendarEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Opt(Time),
          IDL.Opt(Recurrence),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Opt(CalendarEntry)],
        [],
      ),
    'updateCryptoEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Opt(CryptoEntry)],
        [],
      ),
    'updateGoal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time)],
        [IDL.Opt(Goal)],
        [],
      ),
    'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Goal)], []),
    'updateRecurringEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Opt(Time), Recurrence],
        [IDL.Opt(CalendarEntry)],
        [],
      ),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(Time), TaskType],
        [IDL.Opt(Task)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };