/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetItem {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'itemType' : BudgetItemType,
  'amount' : bigint,
}
export type BudgetItemType = { 'expense' : null } |
  { 'income' : null };
export interface CalendarEntry {
  'id' : bigint,
  'startTime' : Time,
  'title' : string,
  'endTime' : [] | [Time],
  'description' : string,
}
export interface CryptoEntry {
  'id' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'currentPriceCents' : bigint,
  'amount' : bigint,
  'purchasePriceCents' : bigint,
  'symbol' : string,
}
export interface Goal {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'progress' : bigint,
  'targetDate' : [] | [Time],
}
export interface Task {
  'id' : bigint,
  'createdAt' : Time,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBudgetItem' : ActorMethod<
    [bigint, string, Time, BudgetItemType],
    BudgetItem
  >,
  'createCalendarEntry' : ActorMethod<
    [string, string, Time, [] | [Time]],
    CalendarEntry
  >,
  'createCryptoEntry' : ActorMethod<
    [string, bigint, bigint, bigint],
    CryptoEntry
  >,
  'createGoal' : ActorMethod<[string, string, [] | [Time]], Goal>,
  'createTask' : ActorMethod<[string, [] | [Time]], Task>,
  'deleteBudgetItem' : ActorMethod<[bigint], undefined>,
  'deleteCalendarEntry' : ActorMethod<[bigint], undefined>,
  'deleteCryptoEntry' : ActorMethod<[bigint], undefined>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getBudgetItems' : ActorMethod<[Principal], Array<BudgetItem>>,
  'getCalendarEntries' : ActorMethod<[Principal], Array<CalendarEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCryptoPortfolio' : ActorMethod<[Principal], Array<CryptoEntry>>,
  'getGoals' : ActorMethod<[Principal], Array<Goal>>,
  'getTasks' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleTaskCompletion' : ActorMethod<[bigint], [] | [Task]>,
  'updateBudgetItem' : ActorMethod<
    [bigint, bigint, string, Time, BudgetItemType],
    [] | [BudgetItem]
  >,
  'updateCalendarEntry' : ActorMethod<
    [bigint, string, string, Time, [] | [Time]],
    [] | [CalendarEntry]
  >,
  'updateCryptoEntry' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    [] | [CryptoEntry]
  >,
  'updateGoal' : ActorMethod<
    [bigint, string, string, [] | [Time]],
    [] | [Goal]
  >,
  'updateGoalProgress' : ActorMethod<[bigint, bigint], [] | [Goal]>,
  'updateTask' : ActorMethod<[bigint, string, [] | [Time]], [] | [Task]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];