/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BudgetItem {
    id: bigint;
    date: Time;
    description: string;
    itemType: BudgetItemType;
    amount: bigint;
}
export interface CalendarEntry {
    id: bigint;
    startTime: Time;
    title: string;
    endTime?: Time;
    description: string;
}
export type Time = bigint;
export interface CryptoEntry {
    id: bigint;
    createdAt: Time;
    updatedAt: Time;
    currentPriceCents: bigint;
    amount: bigint;
    purchasePriceCents: bigint;
    symbol: string;
}
export interface Task {
    id: bigint;
    createdAt: Time;
    completed: boolean;
    dueDate?: Time;
    description: string;
}
export interface UserProfile {
    name: string;
}
export interface Goal {
    id: bigint;
    title: string;
    description: string;
    progress: bigint;
    targetDate?: Time;
}
export enum BudgetItemType {
    expense = "expense",
    income = "income"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBudgetItem(amount: bigint, description: string, date: Time, itemType: BudgetItemType): Promise<BudgetItem>;
    createCalendarEntry(title: string, description: string, startTime: Time, endTime: Time | null): Promise<CalendarEntry>;
    createCryptoEntry(symbol: string, amount: bigint, purchasePriceCents: bigint, currentPriceCents: bigint): Promise<CryptoEntry>;
    createGoal(title: string, description: string, targetDate: Time | null): Promise<Goal>;
    createTask(description: string, dueDate: Time | null): Promise<Task>;
    deleteBudgetItem(itemId: bigint): Promise<void>;
    deleteCalendarEntry(entryId: bigint): Promise<void>;
    deleteCryptoEntry(entryId: bigint): Promise<void>;
    deleteGoal(goalId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    getBudgetItems(user: Principal): Promise<Array<BudgetItem>>;
    getCalendarEntries(user: Principal): Promise<Array<CalendarEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCryptoPortfolio(user: Principal): Promise<Array<CryptoEntry>>;
    getGoals(user: Principal): Promise<Array<Goal>>;
    getTasks(user: Principal): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleTaskCompletion(taskId: bigint): Promise<Task | null>;
    updateBudgetItem(itemId: bigint, amount: bigint, description: string, date: Time, itemType: BudgetItemType): Promise<BudgetItem | null>;
    updateCalendarEntry(entryId: bigint, title: string, description: string, startTime: Time, endTime: Time | null): Promise<CalendarEntry | null>;
    updateCryptoEntry(entryId: bigint, amount: bigint, purchasePriceCents: bigint, currentPriceCents: bigint): Promise<CryptoEntry | null>;
    updateGoal(goalId: bigint, title: string, description: string, targetDate: Time | null): Promise<Goal | null>;
    updateGoalProgress(goalId: bigint, progress: bigint): Promise<Goal | null>;
    updateTask(taskId: bigint, description: string, dueDate: Time | null): Promise<Task | null>;
}
import type { BudgetItem as _BudgetItem, BudgetItemType as _BudgetItemType, CalendarEntry as _CalendarEntry, CryptoEntry as _CryptoEntry, Goal as _Goal, Task as _Task, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBudgetItem(arg0: bigint, arg1: string, arg2: Time, arg3: BudgetItemType): Promise<BudgetItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudgetItem(arg0, arg1, arg2, to_candid_BudgetItemType_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_BudgetItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudgetItem(arg0, arg1, arg2, to_candid_BudgetItemType_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_BudgetItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCalendarEntry(arg0: string, arg1: string, arg2: Time, arg3: Time | null): Promise<CalendarEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createCalendarEntry(arg0, arg1, arg2, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return from_candid_CalendarEntry_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCalendarEntry(arg0, arg1, arg2, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return from_candid_CalendarEntry_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCryptoEntry(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<CryptoEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createCryptoEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCryptoEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: Time | null): Promise<Goal> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Goal_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Goal_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: string, arg1: Time | null): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Task_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Task_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBudgetItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetItem(arg0);
            return result;
        }
    }
    async deleteCalendarEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalendarEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalendarEntry(arg0);
            return result;
        }
    }
    async deleteCryptoEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCryptoEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCryptoEntry(arg0);
            return result;
        }
    }
    async deleteGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getBudgetItems(arg0: Principal): Promise<Array<BudgetItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetItems(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetItems(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCalendarEntries(arg0: Principal): Promise<Array<CalendarEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEntries(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEntries(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoPortfolio(arg0: Principal): Promise<Array<CryptoEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoPortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoPortfolio(arg0);
            return result;
        }
    }
    async getGoals(arg0: Principal): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: Principal): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleTaskCompletion(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompletion(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompletion(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBudgetItem(arg0: bigint, arg1: bigint, arg2: string, arg3: Time, arg4: BudgetItemType): Promise<BudgetItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudgetItem(arg0, arg1, arg2, arg3, to_candid_BudgetItemType_n3(this._uploadFile, this._downloadFile, arg4));
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudgetItem(arg0, arg1, arg2, arg3, to_candid_BudgetItemType_n3(this._uploadFile, this._downloadFile, arg4));
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCalendarEntry(arg0: bigint, arg1: string, arg2: string, arg3: Time, arg4: Time | null): Promise<CalendarEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalendarEntry(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalendarEntry(arg0, arg1, arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4));
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCryptoEntry(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<CryptoEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCryptoEntry(arg0, arg1, arg2, arg3);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCryptoEntry(arg0, arg1, arg2, arg3);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoal(arg0: bigint, arg1: string, arg2: string, arg3: Time | null): Promise<Goal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, arg1, arg2, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, arg1, arg2, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoalProgress(arg0: bigint, arg1: bigint): Promise<Goal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalProgress(arg0, arg1);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalProgress(arg0, arg1);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: Time | null): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BudgetItemType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetItemType): BudgetItemType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetItem): BudgetItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CalendarEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarEntry): CalendarEntry {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BudgetItem]): BudgetItem | null {
    return value.length === 0 ? null : from_candid_BudgetItem_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CalendarEntry]): CalendarEntry | null {
    return value.length === 0 ? null : from_candid_CalendarEntry_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CryptoEntry]): CryptoEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Goal]): Goal | null {
    return value.length === 0 ? null : from_candid_Goal_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    title: string;
    endTime: [] | [_Time];
    description: string;
}): {
    id: bigint;
    startTime: Time;
    title: string;
    endTime?: Time;
    description: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        title: value.title,
        endTime: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.endTime)),
        description: value.description
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    progress: bigint;
    targetDate: [] | [_Time];
}): {
    id: bigint;
    title: string;
    description: string;
    progress: bigint;
    targetDate?: Time;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        progress: value.progress,
        targetDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.targetDate))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: _Time;
    completed: boolean;
    dueDate: [] | [_Time];
    description: string;
}): {
    id: bigint;
    createdAt: Time;
    completed: boolean;
    dueDate?: Time;
    description: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    description: string;
    itemType: _BudgetItemType;
    amount: bigint;
}): {
    id: bigint;
    date: Time;
    description: string;
    itemType: BudgetItemType;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        itemType: from_candid_BudgetItemType_n7(_uploadFile, _downloadFile, value.itemType),
        amount: value.amount
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): BudgetItemType {
    return "expense" in value ? BudgetItemType.expense : "income" in value ? BudgetItemType.income : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BudgetItem>): Array<BudgetItem> {
    return value.map((x)=>from_candid_BudgetItem_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CalendarEntry>): Array<CalendarEntry> {
    return value.map((x)=>from_candid_CalendarEntry_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n15(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetItemType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetItemType): _BudgetItemType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetItemType): {
    expense: null;
} | {
    income: null;
} {
    return value == BudgetItemType.expense ? {
        expense: null
    } : value == BudgetItemType.income ? {
        income: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
